//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DelegacjeProjekt
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transport
    {
        public int IdTransport { get; set; }
        public int IdRozliczenia { get; set; }
        public string ŚrodekTransportu { get; set; }
        public System.DateTime DataPrzejazduOd { get; set; }
        public System.DateTime DataPrzejazduDo { get; set; }
        public string MiejscowośćPrzejazduOd { get; set; }
        public string MiejscowośćPrzejazduDo { get; set; }
        public decimal Koszt { get; set; }
    
        public virtual Koszty Koszty { get; set; }
    }
}
